### ISSUE TITLE
Maintainer needed

### ISSUE THREAD

**Issue by kzyapkov** [ALLTERCO/cc3200tool#23]
This tool was born out of necessity, but is no longer actively used in Allterco. There are now a few pull requests, and a few tasks that need to be done, Python3 support probably being the most important one as well as CC3220 support.

There are now a number of active forks, some of which implement both of the above, as well as other neat features. I wish there was a single, well-maintained, authoritative source where development progresses. This is a callout to @AlexLisnitski, @otsaregorodtsev, @s1ider, @SciLor, @mon and everyone else who contributed to this project in the past -- would you like to take over maintenance and integration of new features?

**Comment by AlexLisnitski** [comment]
Hi guys, me and my team are active users of my cc3200 tool fork. The most
important thing that wasn't work for us in original branch is supporting
cc3220(s) with automatic programming option (using DTR signal). I don't
mind to be involved in supporting of this tool in future however I'm not
sure that I would have a time for this.

Regards,
Alex

**Comment by mon** [comment]
We still use cc3200tool heavily at @MOVUSOZ and are interested in it continuing to exist as we'll use it for at least the next 2 years.

That being said, I can't really handle any of the issues since we don't use the CC3220, gang programming etc. Any maintainership role would likely be limited to reviewing and accepting PRs.

I've also never transferred repo ownership before, but I'd be worried of an org change breaking git URLs - would it be a transfer or adding an admin role to the existing repo?

**Comment by mon** [comment]
Ok, that works for me! Thanks again for the initial work making this exist.
